export type MockTableRow = Record<string, any>;

const now = new Date().toISOString();

const locationPyroStation = {
	id: 'loc_pyro_station',
	slug: 'pyro-gateway-station',
	name_en: 'Pyro Gateway Station',
	name_fr: 'Station Passerelle Pyro',
	system: 'pyro',
	type: 'station',
	difficulty: 'medium',
	description_en: 'A contested station often used as a trading waypoint.',
	description_fr: 'Une station contestée souvent utilisée comme point de commerce.',
	image_url: '/images/locations/pyro-gateway-station.jpg',
	created_at: now
};

const locationBloom = {
	id: 'loc_bloom_outpost',
	slug: 'bloom-mining-outpost',
	name_en: 'Bloom Mining Outpost',
	name_fr: 'Avant-poste Minier Bloom',
	system: 'pyro',
	type: 'outpost',
	difficulty: 'hard',
	description_en: 'Remote outpost with dense hostiles and high-value loot.',
	description_fr: 'Avant-poste reculé avec de nombreux hostiles et du butin de valeur.',
	image_url: '/images/locations/bloom-mining-outpost.jpg',
	created_at: now
};

export const mockDb = {
	rewards: [
		{
			id: 'reward_karna',
			name_en: 'Karna Plasma Rifle',
			name_fr: 'Fusil Plasma Karna',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'epic',
			version: '4.0',
			favor_cost: 120,
			description_en: 'Reliable plasma rifle for medium range combat.',
			description_fr: 'Fusil plasma fiable pour le combat à moyenne portée.',
			image_url: '/images/wikelo/karna.webp',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_polaris',
			name_en: 'Polaris',
			name_fr: 'Polaris',
			type_en: 'Ship',
			type_fr: 'Vaisseau',
			category: 'ships',
			rarity: 'legendary',
			version: '4.0',
			favor_cost: 500,
			description_en: 'Capital patrol corvette reward.',
			description_fr: 'Récompense de corvette de patrouille capitale.',
			image_url: '/images/wikelo/polaris.jpeg',
			has_loadout: true,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_xdl_mark_i_monocular_rangefinder',
			name_en: 'XDL "Mark I" Monocular Rangefinder',
			name_fr: 'XDL "Mark I" Monocular Rangefinder',
			type_en: 'Utility',
			type_fr: 'Utilitaire',
			category: 'utility',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/xdl_mark_1_monocular_rangefinder.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_boomtube_clanguard_rocket_launcher',
			name_en: 'Boomtube "Clanguard" Rocket Launcher',
			name_fr: 'Boomtube "Clanguard" Rocket Launcher',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_parallax_fun_kopion_skull_energy_assault_rifle',
			name_en: 'Parallax "Fun Kopion Skull" Energy Assault Rifle',
			name_fr: 'Parallax "Fun Kopion Skull" Energy Assault Rifle',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_parallax_fun_military_skull_energy_assault_rifle',
			name_en: 'Parallax "Fun Military Skull" Energy Assault Rifle',
			name_fr: 'Parallax "Fun Military Skull" Energy Assault Rifle',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_parallax_fun_kopion_tooth_energy_assault_rifle',
			name_en: 'Parallax "Fun Kopion Tooth" Energy Assault Rifle',
			name_fr: 'Parallax "Fun Kopion Tooth" Energy Assault Rifle',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_parallax_fun_military_tooth_energy_assault_rifle',
			name_en: 'Parallax "Fun Military Tooth" Energy Assault Rifle',
			name_fr: 'Parallax "Fun Military Tooth" Energy Assault Rifle',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_prism_irradiated_laser_shotgun',
			name_en: 'Prism "Irradiated" Laser Shotgun',
			name_fr: 'Prism "Irradiated" Laser Shotgun',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_zenith_snow_camo_laser_sniper_rifle',
			name_en: 'Zenith "Snow Camo" Laser Sniper Rifle',
			name_fr: 'Zenith "Snow Camo" Laser Sniper Rifle',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_fresnel_deepwater_energy_lmg',
			name_en: 'Fresnel "Deepwater" Energy LMG',
			name_fr: 'Fresnel "Deepwater" Energy LMG',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_fresnel_yormandi_lmg',
			name_en: 'Fresnel "Yormandi" LMG',
			name_fr: 'Fresnel "Yormandi" LMG',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_quartz_cobalt_camo_energy_smg',
			name_en: 'Quartz "Cobalt Camo" Energy SMG',
			name_fr: 'Quartz "Cobalt Camo" Energy SMG',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_quartz_jungle_camo_energy_smg',
			name_en: 'Quartz "Jungle Camo" Energy SMG',
			name_fr: 'Quartz "Jungle Camo" Energy SMG',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_quartz_hunter_camo_energy_smg',
			name_en: 'Quartz "Hunter Camo" Energy SMG',
			name_fr: 'Quartz "Hunter Camo" Energy SMG',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_karna_ascension_rifle',
			name_en: 'Karna "Ascension" Rifle',
			name_fr: 'Karna "Ascension" Rifle',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/karna_gun_ascension.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_s71_ascension_rifle',
			name_en: 'S71 "Ascension" Rifle',
			name_fr: 'S71 "Ascension" Rifle',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/s71_riffle_ascension.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_coda_ascension_pistol',
			name_en: 'Coda "Ascension" Pistol',
			name_fr: 'Coda "Ascension" Pistol',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/coda_pistol_ascension.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_f55_mark_i_lmg',
			name_en: 'F55 "Mark I" LMG',
			name_fr: 'F55 "Mark I" LMG',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_tripledown_hot_shot_pistol',
			name_en: 'TripleDown "Hot Shot" Pistol',
			name_fr: 'TripleDown "Hot Shot" Pistol',
			type_en: 'Weapon',
			type_fr: 'Arme',
			category: 'weapons',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_xanthule_ascension_helmet',
			name_en: 'Xanthule Ascension Helmet',
			name_fr: 'Xanthule Ascension Helmet',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_xanthule_ascension_suit',
			name_en: 'Xanthule Ascension Suit',
			name_fr: 'Xanthule Ascension Suit',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_novikov_ascension_helmet',
			name_en: 'Novikov "Ascension" Helmet',
			name_fr: 'Novikov "Ascension" Helmet',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_novikov_ascension_exploration_suit',
			name_en: 'Novikov "Ascension" Exploration Suit',
			name_fr: 'Novikov "Ascension" Exploration Suit',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_venture_helmet_ascension',
			name_en: 'Venture Helmet Ascension',
			name_fr: 'Venture Helmet Ascension',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_venture_arms_ascension',
			name_en: 'Venture Arms Ascension',
			name_fr: 'Venture Arms Ascension',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_venture_core_ascension',
			name_en: 'Venture Core Ascension',
			name_fr: 'Venture Core Ascension',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_venture_legs_ascension',
			name_en: 'Venture Legs Ascension',
			name_fr: 'Venture Legs Ascension',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_palatino_helmet_mark_1',
			name_en: 'Palatino Helmet Mark 1',
			name_fr: 'Palatino Helmet Mark 1',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_palatino_arms_mark_1',
			name_en: 'Palatino Arms Mark 1',
			name_fr: 'Palatino Arms Mark 1',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_palatino_legs_mark_1',
			name_en: 'Palatino Legs Mark 1',
			name_fr: 'Palatino Legs Mark 1',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_palatino_core_mark_1',
			name_en: 'Palatino Core Mark 1',
			name_fr: 'Palatino Core Mark 1',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_palatino_backpack_mark_1',
			name_en: 'Palatino Backpack Mark 1',
			name_fr: 'Palatino Backpack Mark 1',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_geist_armor_helmet_snow_camo',
			name_en: 'Geist Armor Helmet Snow Camo',
			name_fr: 'Geist Armor Helmet Snow Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_geist_backpack_snow_camo',
			name_en: 'Geist Backpack Snow Camo',
			name_fr: 'Geist Backpack Snow Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_geist_armor_arms_snow_camo',
			name_en: 'Geist Armor Arms Snow Camo',
			name_fr: 'Geist Armor Arms Snow Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_geist_armor_core_snow_camo',
			name_en: 'Geist Armor Core Snow Camo',
			name_fr: 'Geist Armor Core Snow Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_geist_armor_legs_snow_camo',
			name_en: 'Geist Armor Legs Snow Camo',
			name_fr: 'Geist Armor Legs Snow Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_corbel_helmet_crush',
			name_en: 'Corbel Helmet Crush',
			name_fr: 'Corbel Helmet Crush',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_corbel_core_crush',
			name_en: 'Corbel Core Crush',
			name_fr: 'Corbel Core Crush',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_corbel_arms_crush',
			name_en: 'Corbel Arms Crush',
			name_fr: 'Corbel Arms Crush',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_corbel_legs_crush',
			name_en: 'Corbel Legs Crush',
			name_fr: 'Corbel Legs Crush',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_novikov_backpack_crush',
			name_en: 'Novikov Backpack Crush',
			name_fr: 'Novikov Backpack Crush',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_testudo_helmet_clanguard',
			name_en: 'Testudo Helmet Clanguard',
			name_fr: 'Testudo Helmet Clanguard',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_testudo_core_clanguard',
			name_en: 'Testudo Core Clanguard',
			name_fr: 'Testudo Core Clanguard',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_testudo_arms_clanguard',
			name_en: 'Testudo Arms Clanguard',
			name_fr: 'Testudo Arms Clanguard',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_testudo_legs_clanguard',
			name_en: 'Testudo Legs Clanguard',
			name_fr: 'Testudo Legs Clanguard',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_testudo_backpack_clanguard',
			name_en: 'Testudo Backpack Clanguard',
			name_fr: 'Testudo Backpack Clanguard',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_dcp_armor_helmet_jungle_camo',
			name_en: 'DCP Armor Helmet Jungle Camo',
			name_fr: 'DCP Armor Helmet Jungle Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_dcp_armor_arms_jungle_camo',
			name_en: 'DCP Armor Arms Jungle Camo',
			name_fr: 'DCP Armor Arms Jungle Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_dcp_armor_core_jungle_camo',
			name_en: 'DCP Armor Core Jungle Camo',
			name_fr: 'DCP Armor Core Jungle Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_dcp_armor_legs_jungle_camo',
			name_en: 'DCP Armor Legs Jungle Camo',
			name_fr: 'DCP Armor Legs Jungle Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_dcp_armor_helmet_hunter_camo',
			name_en: 'DCP Armor Helmet Hunter Camo',
			name_fr: 'DCP Armor Helmet Hunter Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_dcp_armor_arms_hunter_camo',
			name_en: 'DCP Armor Arms Hunter Camo',
			name_fr: 'DCP Armor Arms Hunter Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_dcp_armor_core_hunter_camo',
			name_en: 'DCP Armor Core Hunter Camo',
			name_fr: 'DCP Armor Core Hunter Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_dcp_armor_legs_hunter_camo',
			name_en: 'DCP Armor Legs Hunter Camo',
			name_fr: 'DCP Armor Legs Hunter Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_dcp_armor_helmet_cobalt_camo',
			name_en: 'DCP Armor Helmet Cobalt Camo',
			name_fr: 'DCP Armor Helmet Cobalt Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_dcp_armor_arms_cobalt_camo',
			name_en: 'DCP Armor Arms Cobalt Camo',
			name_fr: 'DCP Armor Arms Cobalt Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_dcp_armor_core_cobalt_camo',
			name_en: 'DCP Armor Core Cobalt Camo',
			name_fr: 'DCP Armor Core Cobalt Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_dcp_armor_legs_cobalt_camo',
			name_en: 'DCP Armor Legs Cobalt Camo',
			name_fr: 'DCP Armor Legs Cobalt Camo',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_ana_armor_helmet_endro',
			name_en: 'Ana Armor Helmet Endro',
			name_fr: 'Ana Armor Helmet Endro',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_ana_armor_core_endro',
			name_en: 'Ana Armor Core Endro',
			name_fr: 'Ana Armor Core Endro',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_ana_armor_arms_endro',
			name_en: 'Ana Armor Arms Endro',
			name_fr: 'Ana Armor Arms Endro',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_ana_armor_legs_endro',
			name_en: 'Ana Armor Legs Endro',
			name_fr: 'Ana Armor Legs Endro',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_bokto_helmet',
			name_en: 'Bokto Helmet',
			name_fr: 'Bokto Helmet',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_bokto_arms',
			name_en: 'Bokto Arms',
			name_fr: 'Bokto Arms',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_bokto_core',
			name_en: 'Bokto Core',
			name_fr: 'Bokto Core',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_bokto_legs',
			name_en: 'Bokto Legs',
			name_fr: 'Bokto Legs',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_strata_helmet_lava',
			name_en: 'Strata Helmet Lava',
			name_fr: 'Strata Helmet Lava',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_strata_arms_lava',
			name_en: 'Strata Arms Lava',
			name_fr: 'Strata Arms Lava',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_strata_core_lava',
			name_en: 'Strata Core Lava',
			name_fr: 'Strata Core Lava',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_strata_legs_lava',
			name_en: 'Strata Legs Lava',
			name_fr: 'Strata Legs Lava',
			type_en: 'Armor',
			type_fr: 'Armure',
			category: 'armor',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_atls_ikti',
			name_en: 'ATLS IKTI',
			name_fr: 'ATLS IKTI',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/atls_ikti.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_atls_geo_ikti',
			name_en: 'ATLS GEO IKTI',
			name_fr: 'ATLS GEO IKTI',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/atls_geo_ikti.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_atls_geo_snowland',
			name_en: 'ATLS GEO "Snowland"',
			name_fr: 'ATLS GEO "Snowland"',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_atls_geo_orange_line',
			name_en: 'ATLS GEO "Orange Line"',
			name_fr: 'ATLS GEO "Orange Line"',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/atls_orange_line.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_atls_geo_cool_metal',
			name_en: 'ATLS GEO "Cool Metal"',
			name_fr: 'ATLS GEO "Cool Metal"',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_nox',
			name_en: 'Nox',
			name_fr: 'Nox',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/nox.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_pulse',
			name_en: 'Pulse',
			name_fr: 'Pulse',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/pulse.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_ursa_medivac',
			name_en: 'Ursa Medivac',
			name_fr: 'Ursa Medivac',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/ursa_medivac.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_l_21_wolf',
			name_en: 'L-21 Wolf',
			name_fr: 'L-21 Wolf',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_golem',
			name_en: 'Golem',
			name_fr: 'Golem',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/golem.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_intrepid',
			name_en: 'Intrepid',
			name_fr: 'Intrepid',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/intrepid.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_fortune',
			name_en: 'Fortune',
			name_fr: 'Fortune',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/fortune.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_c1_spirit',
			name_en: 'C1 Spirit',
			name_fr: 'C1 Spirit',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/c1_spirit.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_zeus_mk_ii_es',
			name_en: 'Zeus Mk II ES',
			name_fr: 'Zeus Mk II ES',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_zeus_mk_ii_cl',
			name_en: 'Zeus Mk II CL',
			name_fr: 'Zeus Mk II CL',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_starlancer_max',
			name_en: 'Starlancer MAX',
			name_fr: 'Starlancer MAX',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_constellation_taurus',
			name_en: 'Constellation Taurus',
			name_fr: 'Constellation Taurus',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_sabre_peregrine',
			name_en: 'Sabre Peregrine',
			name_fr: 'Sabre Peregrine',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_sabre_firebird',
			name_en: 'Sabre Firebird',
			name_fr: 'Sabre Firebird',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_scorpius',
			name_en: 'Scorpius',
			name_fr: 'Scorpius',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_f7c_m_super_hornet_mk_ii',
			name_en: 'F7C-M Super Hornet Mk II',
			name_fr: 'F7C-M Super Hornet Mk II',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_guardian',
			name_en: 'Guardian',
			name_fr: 'Guardian',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_guardian_qi',
			name_en: 'Guardian QI',
			name_fr: 'Guardian QI',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_guardian_mx',
			name_en: 'Guardian MX',
			name_fr: 'Guardian MX',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_f8c_lightning',
			name_en: 'F8C Lightning',
			name_fr: 'F8C Lightning',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_terrapin_medic',
			name_en: 'Terrapin Medic',
			name_fr: 'Terrapin Medic',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_starlancer_tac',
			name_en: 'Starlancer TAC',
			name_fr: 'Starlancer TAC',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_ares_star_fighter_inferno',
			name_en: 'Ares Star Fighter Inferno',
			name_fr: 'Ares Star Fighter Inferno',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_ares_star_fighter_ion',
			name_en: 'Ares Star Fighter Ion',
			name_fr: 'Ares Star Fighter Ion',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_prowler_utility',
			name_en: 'Prowler Utility',
			name_fr: 'Prowler Utility',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_a2_hercules_starlifter',
			name_en: 'A2 Hercules Starlifter',
			name_fr: 'A2 Hercules Starlifter',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_asgard',
			name_en: 'Asgard',
			name_fr: 'Asgard',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_meteor',
			name_en: 'Meteor',
			name_fr: 'Meteor',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_polaris_wikelo_special',
			name_en: 'Polaris_Wikelo_Special',
			name_fr: 'Polaris_Wikelo_Special',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/polaris_bit.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		},
		{
			id: 'reward_idris_p',
			name_en: 'Idris-P',
			name_fr: 'Idris-P',
			type_en: 'Ship/Vehicle',
			type_fr: 'Vaisseau/Véhicule',
			category: 'ships',
			rarity: 'rare',
			version: '4.1',
			favor_cost: 0,
			description_en: 'Reward from Wikelo exchange contracts.',
			description_fr: 'Récompense issue des contrats Wikelo.',
			image_url: '/images/wikelo/unavailable.png',
			has_loadout: false,
			gives: 1,
			not_released: false
		}
	],
	ingredients: [
		{
			id: 'ing_jaclium',
			name_en: 'Jaclium',
			name_fr: 'Jaclium',
			category: 'mineral',
			rarity: 'rare',
			image_url: '/images/wikelo/jaclium.webp',
			description_en: 'A volatile mineral used in advanced crafting.',
			description_fr: 'Un minerai volatil utilisé dans l’artisanat avancé.',
			how_to_obtain_en: 'Mine in Pyro asteroid fields.',
			how_to_obtain_fr: 'Miner dans les champs d’astéroïdes de Pyro.',
			location_id: locationPyroStation.id
		},
		{
			id: 'ing_valakkar_fang',
			name_en: 'Irradiated Valakkar Fang',
			name_fr: 'Croc de Valakkar Irradié',
			category: 'creature',
			rarity: 'epic',
			image_url: '/images/wikelo/irradiated_valakkar_fang_adult.png',
			description_en: 'Rare trophy from dangerous fauna.',
			description_fr: 'Trophée rare provenant d’une faune dangereuse.',
			how_to_obtain_en: 'Loot from irradiated Valakkar encounters.',
			how_to_obtain_fr: 'Butin d’affrontements avec des Valakkars irradiés.',
			location_id: locationBloom.id
		}
	],
	reward_ingredients: [
		{ id: 'ri_1', reward_id: 'reward_karna', ingredient_id: 'ing_jaclium', quantity: 4, unit: 'x' },
		{
			id: 'ri_2',
			reward_id: 'reward_polaris',
			ingredient_id: 'ing_jaclium',
			quantity: 20,
			unit: 'x'
		},
		{
			id: 'ri_3',
			reward_id: 'reward_polaris',
			ingredient_id: 'ing_valakkar_fang',
			quantity: 5,
			unit: 'x'
		}
	],
	reputation_requirements: [
		{
			id: 'rep_req_1',
			reward_id: 'reward_polaris',
			reputation_name_en: 'Council Standing',
			reputation_name_fr: 'Réputation du Conseil',
			required_level: 3
		}
	],
	locations: [locationPyroStation, locationBloom],
	suggestions: [
		{
			id: 'sug_1',
			item_type: 'ingredient',
			item_id: 'ing_jaclium',
			item_name: 'Jaclium',
			suggestion_type: 'location_update',
			content: 'Spawns more frequently around Pyro Gate in 4.0.1.',
			user_email: 'tester@example.com',
			user_id: null,
			created_at: now
		}
	],
	organizations: [
		{
			id: 'org_stanton_scouts',
			name: 'Stanton Scouts',
			slug: 'stanton-scouts',
			description: 'Casual org for exploration and community missions.',
			image_url: null,
			owner_id: 'local-user-1',
			is_public: true,
			created_at: now
		}
	],
	organization_members: [
		{
			id: 'org_mem_1',
			organization_id: 'org_stanton_scouts',
			user_id: 'local-user-1',
			role: 'owner',
			joined_at: now
		}
	],
	organization_join_requests: [],
	profiles: [{ id: 'local-user-1', display_name: 'Local Tester', created_at: now }],
	auth_users: [
		{
			id: 'local-user-1',
			email: 'local@test.lan',
			password: 'admin123',
			approved: true,
			raw_user_meta_data: { role: 'admin', display_name: 'Local Tester' }
		}
	],
	user_inventory: [],
	user_reward_ingredients: [],
	user_reward_completions: [],
	user_favorite_rewards: [],
	user_favorite_ingredients: [],
	user_roles: [{ id: 'role_1', user_id: 'local-user-1', role: 'admin' }]
};

export function getTable(tableName: string): MockTableRow[] {
	if (tableName === 'auth.users') return mockDb.auth_users;
	if (tableName === 'locations_with_ingredients') {
		return mockDb.locations.map((location) => ({
			...location,
			ingredients: mockDb.ingredients
				.filter((ingredient) => ingredient.location_id === location.id)
				.map((ingredient) => ({
					id: ingredient.id,
					name_en: ingredient.name_en,
					name_fr: ingredient.name_fr,
					rarity: ingredient.rarity,
					category: ingredient.category,
					image_url: ingredient.image_url
				}))
		}));
	}
	return (mockDb as Record<string, MockTableRow[]>)[tableName] ?? [];
}
