#!/usr/bin/env python3
"""Import Star Citizen item sheet into SQL seed for items database.

Usage:
  python scripts/import_items_sheet.py > MARIADB_ITEMS_SCHEMA.sql
  python scripts/import_items_sheet.py --csv path/to/items.csv > MARIADB_ITEMS_SCHEMA.sql
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import sys
import urllib.request
from collections import Counter
from pathlib import Path

SHEET_CSV_URL = (
    'https://docs.google.com/spreadsheets/d/1Op0nwuc96ui3QEc9NIB3dqdTwuNB5k5Pv0BieYQINSw/'
    'gviz/tq?tqx=out:csv&sheet=Sheet1'
)

ITEM_TYPES = {
    'ASSULT RIFLE',
    'ASSAULT RIFLE',
    'LMG',
    'PISTOL',
    'SHOTGUN',
    'SMG',
    'SNIPER RIFLE',
    'GRENADE LAUNCHER',
    'RAILGUN',
    'MOUNTED GUN',
    'ROCKET LAUNCHER',
    'MISSLE LAUNCHER',
    'MISSILE LAUNCHER',
    'GRENADE',
    'UTILITY',
    'CONSUMABLE',
    'MINE',
    'GADGET',
}


def esc(v: str) -> str:
    return v.replace('\\', '\\\\').replace("'", "''")


def slug(v: str) -> str:
    out = ''.join(ch.lower() if ch.isalnum() else '_' for ch in v)
    while '__' in out:
        out = out.replace('__', '_')
    return out.strip('_') or 'item'


def make_id(item_type: str, name: str, fire_mode: str, row_num: int) -> str:
    base = f"item_{slug(item_type)}_{slug(name)}_{slug(fire_mode)}_{row_num}"
    if len(base) <= 64:
        return base
    digest = hashlib.sha1(base.encode('utf-8')).hexdigest()[:12]
    head = f"item_{slug(item_type)}_{slug(name)}"
    head = head[: (64 - 1 - 12)]
    return f"{head}_{digest}"[:64]


def load_csv_text(path: str | None) -> str:
    if path:
        return Path(path).read_text(encoding='utf-8')
    with urllib.request.urlopen(SHEET_CSV_URL, timeout=60) as resp:
        return resp.read().decode('utf-8-sig')


def parse_rows(csv_text: str) -> tuple[list[str], list[dict]]:
    reader = csv.reader(io.StringIO(csv_text))
    rows = list(reader)
    if not rows:
        return [], []
    header = rows[0]
    # First column is usually "Item <TYPE>" and indicates current section category.
    first_col = (header[0] if header else '').strip().upper()
    current_type = ''
    if first_col.startswith('ITEM '):
        initial_type = first_col.replace('ITEM ', '', 1).strip()
        if initial_type in ITEM_TYPES:
            current_type = initial_type

    # Preserve duplicate header names by suffixing duplicates with __N.
    normalized_header: list[str] = []
    seen: Counter[str] = Counter()
    for i, col in enumerate(header):
        base = (col or '').strip() or f'col_{i+1}'
        seen[base] += 1
        normalized_header.append(base if seen[base] == 1 else f'{base}__{seen[base]}')

    data_rows = rows[1:]

    parsed: list[dict] = []

    for idx, row in enumerate(data_rows, start=2):
        if not any(cell.strip() for cell in row):
            continue

        item_cell = (row[0] if len(row) > 0 else '').strip()
        fire_mode = (row[7] if len(row) > 7 else '').strip()  # Column H

        upper_item = item_cell.upper()
        if upper_item.startswith('ITEM '):
            maybe_type = upper_item.replace('ITEM ', '', 1).strip()
            if maybe_type in ITEM_TYPES:
                current_type = maybe_type
            continue
        if upper_item in ITEM_TYPES:
            current_type = upper_item
            continue

        if not item_cell:
            continue

        values = row + [''] * max(0, len(normalized_header) - len(row))
        payload = {normalized_header[i]: values[i] for i in range(len(normalized_header))}

        parsed.append(
            {
                'row_number': idx,
                'item_name': item_cell,
                'item_type': current_type or 'UNKNOWN',
                'fire_mode': fire_mode,
                'payload': payload,
            }
        )

    # Separate multiple entries by fire mode
    counts = Counter(p['item_name'].strip().lower() for p in parsed)
    for p in parsed:
        display_name = p['item_name']
        if counts[p['item_name'].strip().lower()] > 1:
            suffix = p['fire_mode'] or 'Unknown Fire Mode'
            display_name = f"{display_name} ({suffix})"
        p['display_name'] = display_name
        p['id'] = make_id(p['item_type'], p['display_name'], p['fire_mode'], p['row_number'])

    return header, parsed


def emit_sql(header: list[str], parsed: list[dict]) -> str:
    out: list[str] = []
    out.append('-- Auto-generated by scripts/import_items_sheet.py')
    out.append('CREATE TABLE IF NOT EXISTS items_database (')
    out.append('  id VARCHAR(64) PRIMARY KEY,')
    out.append('  item_name VARCHAR(255) NOT NULL,')
    out.append('  base_item_name VARCHAR(255) NOT NULL,')
    out.append('  item_type VARCHAR(64) NOT NULL,')
    out.append('  fire_mode VARCHAR(64) NULL,')
    out.append('  source_row INT NOT NULL,')
    out.append('  data_json LONGTEXT NOT NULL,')
    out.append('  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,')
    out.append('  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,')
    out.append('  INDEX idx_items_database_name (item_name),')
    out.append('  INDEX idx_items_database_base_name (base_item_name),')
    out.append('  INDEX idx_items_database_type (item_type),')
    out.append('  INDEX idx_items_database_fire_mode (fire_mode)')
    out.append(');\n')

    out.append('INSERT INTO items_database (id, item_name, base_item_name, item_type, fire_mode, source_row, data_json) VALUES')
    rows_sql = []
    for p in parsed:
        data_json = json.dumps(p['payload'], ensure_ascii=False)
        fire_mode = 'NULL' if not p['fire_mode'] else f"'{esc(p['fire_mode'])}'"
        rows_sql.append(
            "  ('{id}','{item_name}','{base}','{item_type}',{fire_mode},{source_row},'{data_json}')".format(
                id=esc(p['id']),
                item_name=esc(p['display_name']),
                base=esc(p['item_name']),
                item_type=esc(p['item_type']),
                fire_mode=fire_mode,
                source_row=p['row_number'],
                data_json=esc(data_json),
            )
        )
    out.append(',\n'.join(rows_sql))
    out.append('ON DUPLICATE KEY UPDATE')
    out.append('  item_name=VALUES(item_name),')
    out.append('  base_item_name=VALUES(base_item_name),')
    out.append('  item_type=VALUES(item_type),')
    out.append('  fire_mode=VALUES(fire_mode),')
    out.append('  source_row=VALUES(source_row),')
    out.append('  data_json=VALUES(data_json);')

    return '\n'.join(out) + '\n'


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--csv', dest='csv_path', default=None, help='Path to local CSV export')
    parser.add_argument('--out', dest='out_path', default='MARIADB_ITEMS_SCHEMA.sql', help='Output SQL file')
    args = parser.parse_args()

    csv_text = load_csv_text(args.csv_path)
    header, parsed = parse_rows(csv_text)
    if not parsed:
        print('No item rows parsed from source sheet.', file=sys.stderr)
        return 1

    sql = emit_sql(header, parsed)
    Path(args.out_path).write_text(sql, encoding='utf-8')
    print(f'Wrote {args.out_path} with {len(parsed)} item rows.', file=sys.stderr)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
