#!/usr/bin/env python3
"""Transform datamined Wikelo JSON into SQL upserts for this repo schema.
Usage:
  python scripts/import_wikelo_datamine.py path/to/wikelo.json > data/wikelo_datamine_seed.sql
"""
import json, re, sys
from pathlib import Path

def slug(v:str)->str:
    v=v.strip().lower()
    v=re.sub(r"[^a-z0-9]+","_",v)
    return re.sub(r"_+","_",v).strip("_") or "unknown"

def esc(v:str)->str:
    return v.replace("\\","\\\\").replace("'","''")

def parse_recipe(recipe:str):
    out=[]
    if not recipe: return out
    for part in [p.strip() for p in recipe.split(';') if p.strip()]:
        m=re.match(r"^(\d+)x\s+(.+)$",part)
        if m:
            qty=int(m.group(1)); name=m.group(2).strip()
        else:
            qty=1; name=part
        out.append((name,qty))
    return out

def rarity_from_status(status:str)->str:
    m={"active":"epic","retired-store":"rare","retired-loot":"uncommon"}
    return m.get((status or "").lower(),"common")

def to_reward_row(entry,prefix):
    rid=f"{prefix}_{entry.get('id') or slug(entry.get('mission_name','reward'))}"
    type_en=(entry.get('category') or 'item').replace('-', ' ').title()
    cat=(entry.get('category') or 'utilities').lower()
    if cat in ('weapon',): cat='weapons'
    if cat in ('ship',): cat='ships'
    if cat in ('vehicle',): cat='vehicles'
    if cat in ('armor','gear','item','currency','intro'): cat='utilities'
    return {
      'id': rid,
      'name_en': (entry.get('reward') or entry.get('name') or entry.get('mission_name') or rid).strip()[:255],
      'type_en': type_en[:255],
      'category': cat,
      'rarity': rarity_from_status(entry.get('status','')),
      'version': '4.6',
      'description_en': (entry.get('description') or '').strip(),
      'image_url': ('/' + entry.get('image_url').lstrip('/')) if entry.get('image_url') else None,
      'mission_name_en': (entry.get('mission_name') or '').strip()[:255],
      'has_loadout': 1 if entry.get('category') in ('ship','vehicle') else 0,
      'gives': 1,
      'not_released': 0,
      'rep': int(entry.get('reputation_required') or 0)
    }

def main():
    if len(sys.argv)<2:
        print('usage: import_wikelo_datamine.py <json_file>',file=sys.stderr); sys.exit(2)
    data=json.loads(Path(sys.argv[1]).read_text())
    entries=list(data.get('items',[]))+list(data.get('ships',[]))
    if data.get('intro_mission'): entries.append(data['intro_mission'])
    for ex in data.get('currency_exchanges',[]):
        entries.append({
          'id': f"exchange_{slug(ex.get('mission_name','exchange'))}",
          'name': ex.get('mission_name','Exchange'),
          'category':'currency','status':'active','mission_name':ex.get('mission_name','Exchange'),
          'recipe': ex.get('recipe',''), 'reward': ex.get('reward',''),
          'description': ex.get('description',''), 'reputation_required':0
        })

    rewards=[]; ingredients={}; reqs=[]; reps=[]
    for e in entries:
        r=to_reward_row(e,'reward_dm')
        rewards.append(r)
        for name,qty in parse_recipe(e.get('recipe','')):
            iid='ing_dm_'+slug(name)
            ingredients[iid]=name
            reqs.append((f"ri_{slug(r['id'])}_{slug(iid)}", r['id'], iid, qty, 'x'))
        if r['rep']>0:
            reps.append((f"rep_{slug(r['id'])}", r['id'], 'Wikelo Reputation', 'Réputation Wikelo', r['rep']))

    print('-- Datamined Wikelo 4.6 seed generated by scripts/import_wikelo_datamine.py')
    print('INSERT INTO rewards (id,name_en,name_fr,type_en,type_fr,category,rarity,version,favor_cost,description_en,description_fr,image_url,image_credit,mission_name_en,mission_name_fr,has_loadout,gives,not_released) VALUES')
    reward_rows=[]
    for r in rewards:
        image = 'NULL' if not r['image_url'] else "'" + esc(r['image_url']) + "'"
        reward_rows.append(
            "  ('{id}','{name}','{name}','{type}','{type}','{category}','{rarity}','{version}',NULL,'{desc}','{desc}',{image},NULL,'{mission}','{mission}',{has_loadout},{gives},{not_released})".format(
                id=esc(r['id']),
                name=esc(r['name_en']),
                type=esc(r['type_en']),
                category=esc(r['category']),
                rarity=esc(r['rarity']),
                version=esc(r['version']),
                desc=esc(r['description_en']),
                image=image,
                mission=esc(r['mission_name_en']),
                has_loadout=r['has_loadout'],
                gives=r['gives'],
                not_released=r['not_released']
            )
        )
    print(',\n'.join(reward_rows))
    print('ON DUPLICATE KEY UPDATE name_en=VALUES(name_en),name_fr=VALUES(name_fr),type_en=VALUES(type_en),type_fr=VALUES(type_fr),category=VALUES(category),rarity=VALUES(rarity),version=VALUES(version),description_en=VALUES(description_en),description_fr=VALUES(description_fr),image_url=VALUES(image_url),mission_name_en=VALUES(mission_name_en),mission_name_fr=VALUES(mission_name_fr),has_loadout=VALUES(has_loadout),gives=VALUES(gives),not_released=VALUES(not_released);\n')

    print('INSERT INTO ingredients (id,name_en,name_fr,category,rarity,image_url,description_en,description_fr,how_to_obtain_en,how_to_obtain_fr,location_id) VALUES')
    ingredient_rows=["  ('{iid}','{name}','{name}','special','common',NULL,NULL,NULL,NULL,NULL,NULL)".format(iid=esc(iid),name=esc(name)) for iid,name in sorted(ingredients.items())]
    print(',\n'.join(ingredient_rows))
    print('ON DUPLICATE KEY UPDATE name_en=VALUES(name_en),name_fr=VALUES(name_fr),category=VALUES(category),rarity=VALUES(rarity);\n')

    print('INSERT INTO reward_ingredients (id,reward_id,ingredient_id,quantity,unit) VALUES')
    req_rows=["  ('{a}','{b}','{c}',{d},'{e}')".format(a=esc(a),b=esc(b),c=esc(c),d=d,e=e) for a,b,c,d,e in reqs]
    print(',\n'.join(req_rows))
    print('ON DUPLICATE KEY UPDATE reward_id=VALUES(reward_id),ingredient_id=VALUES(ingredient_id),quantity=VALUES(quantity),unit=VALUES(unit);\n')

    if reps:
        print('INSERT INTO reputation_requirements (id,reward_id,reputation_name_en,reputation_name_fr,required_level) VALUES')
        rep_rows=["  ('{a}','{b}','{c}','{d}',{e})".format(a=esc(a),b=esc(b),c=esc(c),d=esc(d),e=e) for a,b,c,d,e in reps]
        print(',\n'.join(rep_rows))
        print('ON DUPLICATE KEY UPDATE reward_id=VALUES(reward_id),reputation_name_en=VALUES(reputation_name_en),reputation_name_fr=VALUES(reputation_name_fr),required_level=VALUES(required_level);')

if __name__=='__main__':
    main()
